org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.home=C\:\\Program Files\\Java\\jdk-21

mod_version = 1.0.0
maven_group = com.aguilam
archives_name = blockberg_terminal
enabled_platforms = fabric,neoforge

minecraft_version=1.21.1

fabric_loader_version=0.16.10
fabric_version=0.114.0+1.21.1
yacl_version=3.8.1+1.21.1-fabric
modmenu_version=11.0.3

neoforge_version = 21.1.248