org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.home=C\:\\Program Files\\Java\\jdk-21

yarn_mappings=1.21.3+build.2

mod_version = 1.0.0
maven_group = com.aguilam
archives_name = blockberg_terminal
enabled_platforms = fabric

minecraft_version=1.21.3

fabric_loader_version=0.16.10
fabric_version=0.114.0+1.21.3
yacl_version=3.6.1+1.21.2-fabric
modmenu_version=12.0.1

forge_version = 1.20.1-47.4.10